name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest

    environment:
      name: my-awesome-environment-for-test

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump env
        run: echo '${{ toJSON(env) }}'
      - name: Dump vars
        run: echo '${{ toJSON(vars) }}'
